<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ModAssets</RootNamespace>
        <LangVersion>latest</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Content\Lua\Scripts\Client\**" />
      <Compile Remove="Content\Lua\Scripts\Server\**" />
      <EmbeddedResource Remove="Content\Lua\Scripts\Client\**" />
      <EmbeddedResource Remove="Content\Lua\Scripts\Server\**" />
      <None Remove="Content\Lua\Scripts\Client\**" />
      <None Remove="Content\Lua\Scripts\Server\**" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Content\DefaultConfigs\" />
    </ItemGroup>

    <Import Project="../Build.props" />

    <Target Name="CopyFiles" AfterTargets="Build">
        <ItemGroup>
            <Content Include="$(ProjectDir)Content\**\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(Content)" DestinationFolder="$(ModDeployDir)%(RecursiveDir)" />
    </Target>
</Project>
